### ISSUE TITLE
Firebase: IT Express not being fetched

### ISSUE THREAD

**Issue by sabin-thapa** [kucc1997/kucc-website#40]
The IT Express files from the Firebase storage are not being fetched.
![image](https://user-images.githubusercontent.com/51270026/193607996-bbafe77e-5dd8-4629-b3d0-4f29fe807d01.png)

**Comment by Aryashakya** [comment]
This bug is caused as the .env file was deleted in commit `a5a87e0`. 

Restoring the .env file resolves this issue. #42 I have restored .env file in this PR 

But there is still another issue as Firebase does not have the required permissions as shown below: 

![image](https://user-images.githubusercontent.com/67620278/194539915-2ef2dbdf-ba01-4f54-a250-ddf5267981a0.png)

**Comment by sabin-thapa** [comment]
> This bug is caused as the .env file was deleted in commit `a5a87e0`.
> 
> Restoring the .env file resolves this issue. #42 I have restored .env file in this PR
> 
> But there is still another issue as Firebase does not have the required permissions as shown below:
> 
> ![image](https://user-images.githubusercontent.com/67620278/194539915-2ef2dbdf-ba01-4f54-a250-ddf5267981a0.png)

Great job, @Aryashakya ! The new issue will be solved by changing the database rules. So, I'll mark this issue as resolved for now.
